language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install:
 - "pip install -r requirements.txt"

# command to run tests
script: nosetests

notifications:
  email:
    - apussapus@gmail.com

after_success:
  - coveralls
